Welcome to Maritime Resource Name Registry. This page is just getting started (February 2017). But it is our goal to be able to provide up to date information about Maritime Resource Names and the usage of them within the maritime industry.

The usage of Maritime Resource Names are currently in the process of being standardized and we expect this to be finalized in early 2018. The first draft of our proposal for MRNs is up at https://tools.ietf.org/html/draft-knielsen-mrn-urn-00

We expect to work through a number of drafts. And we will welcome comments and contributions either by signing up to our discussion group at https://groups.google.com/forum/#!forum/mrn-discuss or by emailing the author directly (kasperni@gmail.com).

== What is Maritime Resource Names
Maritime Resource Names (MRN) is a naming scheme that can uniquely identify any maritime resource on a global scale. By maritime resource we basically mean anything that has an identity of some kind. This could be organizations, employees, a person, a physical or a virtual object, for instance an electronic document, a buoy, a ship, a mariner, a nautical chart or an electronic service (e.g., "today's weather report for the Oresund Strait"). Not all resources are "retrievable" in an electronic sense; For example, human beings, corporations, and buoys. However, they can still be considered a resource.

http://www.ietf.org/id/draft-nielsen-mrn-urn-00.txt provides a more detailed explanation of the concept and a number of examples.

== Who is using it
We are currently getting some experience using MRNs in the following projects
|===
|Who | What For
|http://efficiensea2.org/ | For identification of users, organizations and services
|http://stmvalidation.eu/ | For identification of organizations, services and voyages
|Smart Navigation | For identification of users

|IALA ENAV | MSP8 Vessel Shore Reporting Service
|===

Readers may send feedback about errors, omissions, and ambiguities on this page to kasperni@gmail.com
